services:
  mycontainer:
    build: .
    image: "docker.io/0xswayam/my-app:latest"   # Always provide FQDN image names!
    platform: linux/amd64
    ports:
      - "3000:3000"                              # Expose ENS resolver API
    volumes:
      - my-volume:/root/.my-volume              # Persistent per-machine storage.
      - /run/rofl-appd.sock:/run/rofl-appd.sock # appd REST API.
    environment:
      - PORT=3000
      - DB_PATH=/root/.my-volume/database.db
      - PRIVATE_KEY=${PRIVATE_KEY}              # Required: ENS resolver private key
      - MY_SECRET_1=${MY_SECRET_1}              # See `oasis rofl secret` command.
      - MY_SECRET_2=${MY_SECRET_2}

volumes:
  my-volume:
